name: Test Nu@npm

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    paths-ignore:
      - '**.md'

jobs:
  test-latest:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Test (${{matrix.os}}, nu@npm)
    steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    - name: Test Nu Install from NPM Registry
      run: |
        npm i --location=global nushell@latest --registry https://registry.npmjs.org
        nu -c "print $'Nu version info:(char nl)'; print (version)"

  none-x64-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Running NU on ${{ matrix.distro }} ${{ matrix.arch }}
    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: armv6
            distro: ubuntu_latest
          - arch: armv7
            distro: ubuntu_latest
          - arch: aarch64
            distro: ubuntu_latest

    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Nu From Npm Check
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            npm i --location=global nushell@latest --registry https://registry.npmjs.org
            nu -c "print $'Nu version info:(char nl)'; print (version)"


