name: Test Nu@npm

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    paths-ignore:
      - '**.md'

jobs:
  test-latest:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Test Nu@npm on ${{matrix.os}}_x64
    steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    - name: Test Nu Install from NPM Registry
      run: |
        npm i --location=global nushell@latest --registry https://registry.npmjs.org
        nu -c "print $'Nu version info:(char nl)'; print (version)"

  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 armv7
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu22.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

  none-x64-check:
    runs-on: ubuntu-latest
    name: Test Nu@npm on ${{ matrix.distro }}_${{ matrix.arch }}
    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv7
            distro: ubuntu22.04
          - arch: aarch64
            distro: ubuntu22.04
          - arch: riscv64
            distro: ubuntu22.04

    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Test Install Nu@npm on ${{matrix.os}}_${{ matrix.distro }}
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            # apt install -y nodejs
            # npm i --location=global nushell@latest --registry https://registry.npmjs.org
            # nu -c "print $'Nu version info:(char nl)'; print (version)"


