name: Release nu to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-npm-binaries:
    name: Publish NPM packages
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - uses: hustcer/setup-nu@v3
        with:
          version: 0.78

      - name: Publish to NPM
        run: nu nu/npm.nu
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-npm-base:
    name: Publish the base NPM package
    needs: publish-npm-binaries
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish the package
        continue-on-error: true
        shell: bash
        run: |
          cp README.* npm/app/
          cd npm/app
          aria2c https://raw.githubusercontent.com/nushell/nushell/main/LICENSE
          yarn install  # requires optional dependencies to be present in the registry
          yarn build
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
